CREATE DATABASE IF NOT EXISTS FIGURES;

USE FIGURES;

CREATE TABLE FIGURA (
    id INT AUTO INCREMENT PRIMARY KEY,
    meshID VARCHAR(16) UNIQUE NOT NULL,
    nom VARCHAR(16) NOT NULL,
    descript VARCHAR(40) NULL
) 

CREATE TABLE OMBRA (
    id INT AUTO INCREMENT PRIMARY KEY,
    meshID VARCHAR(16) NOT NULL,
    imgID VARCHAR(16) NOT NULL
    nom VARCHAR(16) NOT NULL, 
)