CREATE DATABASE IF NOT EXISTS FIGURES
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE FIGURES;

CREATE TABLE OMBRA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    meshID VARCHAR(16) NOT NULL,
    imgID VARCHAR(16) NOT NULL,
    nom VARCHAR(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE FIGURA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    meshID VARCHAR(16) UNIQUE NOT NULL,
    nom VARCHAR(16) NOT NULL,
    descript VARCHAR(40) NULL,
    alzada INT NOT NULL,
    planta INT NOT NULL,
    perfil INT NOT NULL,
    CONSTRAINT fk_alzada FOREIGN KEY (alzada) REFERENCES OMBRA(id),
    CONSTRAINT fk_planta FOREIGN KEY (planta) REFERENCES OMBRA(id),
    CONSTRAINT fk_perfil FOREIGN KEY (perfil) REFERENCES OMBRA(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;